# full list: https://domluna.github.io/JuliaFormatter.jl/dev/#Formatting-Options
style = "sciml"
yas_style_nesting = true # special for this style
margin = 92
always_for_in = true
normalize_line_endings = "unix"
whitespace_in_kwargs = false
whitespace_typedefs = false
whitespace_ops_in_indices = false
format_markdown = true
format_docstrings = true
join_lines_based_on_source = true
remove_extra_newlines = false

align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = true

# indent = 4,
# margin = 92,
# always_for_in = false,
# for_in_replacement = "in",
# whitespace_typedefs = false,
# whitespace_ops_in_indices = false,
# remove_extra_newlines = false,
# import_to_using = false,
# pipe_to_function_call = false,
# short_to_long_function_def = false,
# long_to_short_function_def = false,
# always_use_return = false,
# whitespace_in_kwargs = true,
# annotate_untyped_fields_with_any = true,
# format_docstrings = false,
# align_struct_field = false,
# align_conditional = false,
# align_assignment = false,
# align_pair_arrow = false,
# conditional_to_if = false,
# normalize_line_endings = "auto",
# align_matrix = false,
# trailing_comma = false,
# trailing_zero = true,
# indent_submodule = false,
# separate_kwargs_with_semicolon = false,
# surround_whereop_typeparameters = true,
# variable_call_indent = []
# short_circuit_to_if = false,
