name: Benchmark a pull request

on:
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # always cancel old runs on new push

permissions:
  pull-requests: write
  actions: write
  contents: read

jobs:
  check_skip: # check for "[no benchmark]" in pr body
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip_benchmark }}
    steps:
      - name: Fetch latest PR details
        id: fetch-pr
        run: |
          PR_DATA=$(gh pr view ${{ github.event.pull_request.number }} --json body,title -q '{body: .body, title: .title}')
          echo "PR_TITLE=$(echo $PR_DATA | jq -r '.title')" >> $GITHUB_ENV
          echo "PR_BODY=$(echo $PR_DATA | jq -r '.body')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for '[no benchmark]'
        id: check
        run: |
          if [[ "$PR_TITLE" == *"[no benchmark]"* || "$PR_BODY" == *"[no benchmark]"* ]]; then
            echo "Benchmarks will be skipped."
            echo "skip_benchmark=true" >> $GITHUB_OUTPUT
          else
            echo "Benchmarks will run."
            echo "skip_benchmark=false" >> $GITHUB_OUTPUT
          fi

  run_benchmarks:
    needs: check_skip
    if: needs.check_skip.outputs.skip == 'false' # Skip the job if '[no benchmark]' is found
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run benchmarks
        env:
          JULIA_NUM_THREADS: auto
        working-directory: benchmark
        run: |
          julia --color=yes ./run_benchmarks.jl -t ${{github.event.pull_request.head.ref}} -b ${{github.event.pull_request.base.ref}} --no-data-export --prefix ""
          echo '<details>' > body.md
          echo '<summary>Benchmark Results</summary>' > body.md
          echo '' >> body.md
          echo '```' >> body.md
          cat comparison.txt >> body.md
          echo '```' >> body.md
          echo '' >> body.md
          echo '</details>' > body.md
          echo '' >> body.md
      - name: Upload plot
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: comparison.pdf
          path: benchmark/comparison.pdf
      - name: Link to graphic
        run: |
          echo '${{ steps.artifact-upload-step.outputs.artifact-url }}' >> benchmark/body.md
      - uses: int128/hide-comment-action@v1 # hide all previous comments
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: benchmark/body.md
